steps:
- name: Setup Secrets
  - shell: bash
  env: # Or as an environment variable
    CLIENDID: ${{ secrets.CLIENTID }}
    CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
    SECRETID: ${{ secrets.SECRETID }}